@IsTest
public class DAO_GenericDmlIntTest {
    private static final User TEST_ADMIN = XFTY_DummyUserFactoryOutlet.TEST_ADMIN_USER;

    @IsTest public static void testDoInsertShouldInsertValidRecordsWhenAllOrNone() {/* TODO */}
    @IsTest public static void testDoInsertShouldInsertValidRecordsWhenNotAllOrNone() {/* TODO */}
    @IsTest public static void testDoInsertShouldThrowExceptionForInvalidRecordsWhenAllOrNone() {/* TODO */}
    @IsTest public static void testDoInsertShouldThrowExceptionForInvalidRecordsWhenNotAllOrNone() {/* TODO */}
}